// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyART6YbQA5mSz5pVQB_jLf5OiKo_mu_KBw',
    appId: '1:475364726705:web:27024c188eff5802bc4f90',
    messagingSenderId: '475364726705',
    projectId: 'dreamera-b079a',
    authDomain: 'dreamera-b079a.firebaseapp.com',
    storageBucket: 'dreamera-b079a.firebasestorage.app',
    measurementId: 'G-D2ZQ383Z6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzGhBqxp1cTq9zg-A68lqo0hCnL435dJc',
    appId: '1:475364726705:android:31d4ba424263ac7fbc4f90',
    messagingSenderId: '475364726705',
    projectId: 'dreamera-b079a',
    storageBucket: 'dreamera-b079a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuJc56g5sC_t8C2sJfglK1upl45DjrEQE',
    appId: '1:475364726705:ios:a2c6bc3112de45f8bc4f90',
    messagingSenderId: '475364726705',
    projectId: 'dreamera-b079a',
    storageBucket: 'dreamera-b079a.firebasestorage.app',
    iosBundleId: 'com.example.dreamera',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuJc56g5sC_t8C2sJfglK1upl45DjrEQE',
    appId: '1:475364726705:ios:a2c6bc3112de45f8bc4f90',
    messagingSenderId: '475364726705',
    projectId: 'dreamera-b079a',
    storageBucket: 'dreamera-b079a.firebasestorage.app',
    iosBundleId: 'com.example.dreamera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyART6YbQA5mSz5pVQB_jLf5OiKo_mu_KBw',
    appId: '1:475364726705:web:bedac33ee5a2df88bc4f90',
    messagingSenderId: '475364726705',
    projectId: 'dreamera-b079a',
    authDomain: 'dreamera-b079a.firebaseapp.com',
    storageBucket: 'dreamera-b079a.firebasestorage.app',
    measurementId: 'G-Y1HWG7WJ7M',
  );
}
