// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKQxukPBcwoS3mHIYIGNNE6tqeCNAupp0',
    appId: '1:790663387405:web:399b42f1092d7f6694b844',
    messagingSenderId: '790663387405',
    projectId: 'dream-scape-dfde3',
    authDomain: 'dream-scape-dfde3.firebaseapp.com',
    storageBucket: 'dream-scape-dfde3.firebasestorage.app',
    measurementId: 'G-MECB9VCHCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIjpGg3EB-gRn3nHUO0ifZJeqXOW3Vg6M',
    appId: '1:790663387405:android:50fbed2b072b806994b844',
    messagingSenderId: '790663387405',
    projectId: 'dream-scape-dfde3',
    storageBucket: 'dream-scape-dfde3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYj2hDOaZUacHyBC0iHoDk0ZTKLL_lf7Q',
    appId: '1:790663387405:ios:434a38bc2a1081a094b844',
    messagingSenderId: '790663387405',
    projectId: 'dream-scape-dfde3',
    storageBucket: 'dream-scape-dfde3.firebasestorage.app',
    androidClientId: '790663387405-shatafr8fbp6c94g86537ppfnht7dqkf.apps.googleusercontent.com',
    iosClientId: '790663387405-clu8r246r3jgsd77g80d2d1q7ipops85.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreamScape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYj2hDOaZUacHyBC0iHoDk0ZTKLL_lf7Q',
    appId: '1:790663387405:ios:434a38bc2a1081a094b844',
    messagingSenderId: '790663387405',
    projectId: 'dream-scape-dfde3',
    storageBucket: 'dream-scape-dfde3.firebasestorage.app',
    androidClientId: '790663387405-shatafr8fbp6c94g86537ppfnht7dqkf.apps.googleusercontent.com',
    iosClientId: '790663387405-clu8r246r3jgsd77g80d2d1q7ipops85.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreamScape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKQxukPBcwoS3mHIYIGNNE6tqeCNAupp0',
    appId: '1:790663387405:web:756010361f1705cd94b844',
    messagingSenderId: '790663387405',
    projectId: 'dream-scape-dfde3',
    authDomain: 'dream-scape-dfde3.firebaseapp.com',
    storageBucket: 'dream-scape-dfde3.firebasestorage.app',
    measurementId: 'G-XFRDCLE1F7',
  );
}
